import path from "node:path";
import { defineConfig } from "@playwright/test";

const PORT = 3222;
const MONO_PORT = 3223;
const fixtureDir = path.join(process.cwd(), "tests", "fixtures", "sample-nextjs");
const monorepoFixtureDir = path.join(process.cwd(), "tests", "fixtures", "sample-monorepo");

/**
 * E2E runs against production builds with deterministic fixture providers, so
 * no GitHub API traffic is generated by automated tests. Two servers are used:
 * a single-package Next.js fixture and a monorepo fixture.
 *
 * Requires a prior `npm run build`. Uses the locally installed Edge browser
 * (channel: msedge) to avoid downloading browser binaries.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 120_000,
  expect: { timeout: 20_000 },
  fullyParallel: false,
  workers: 1,
  reporter: [["list"]],
  use: {
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "msedge",
      testIgnore: /packages\.spec\.ts/,
      use: {
        channel: "msedge",
        viewport: { width: 1440, height: 900 },
        baseURL: `http://127.0.0.1:${PORT}`,
      },
    },
    {
      name: "msedge-monorepo",
      testMatch: /packages\.spec\.ts/,
      use: {
        channel: "msedge",
        viewport: { width: 1440, height: 900 },
        baseURL: `http://127.0.0.1:${MONO_PORT}`,
      },
    },
  ],
  webServer: [
    {
      command: `node node_modules/next/dist/bin/next start -p ${PORT}`,
      url: `http://127.0.0.1:${PORT}/api/health`,
      reuseExistingServer: false,
      timeout: 120_000,
      env: {
        APPGRAPH_FIXTURE_DIR: fixtureDir,
        APPGRAPH_ANALYSIS_VERSION: "e2e",
        APPGRAPH_CACHE_DIR: path.join(process.cwd(), ".appgraph-cache-e2e"),
        APPGRAPH_ANALYZE_RATE_LIMIT: "200",
        APPGRAPH_MAX_CONCURRENT_ANALYSES: "2",
        ...(process.env.NEXT_DIST_DIR ? { NEXT_DIST_DIR: process.env.NEXT_DIST_DIR } : {}),
      },
    },
    {
      command: `node node_modules/next/dist/bin/next start -p ${MONO_PORT}`,
      url: `http://127.0.0.1:${MONO_PORT}/api/health`,
      reuseExistingServer: false,
      timeout: 120_000,
      env: {
        APPGRAPH_FIXTURE_DIR: monorepoFixtureDir,
        APPGRAPH_ANALYSIS_VERSION: "e2e-mono",
        APPGRAPH_CACHE_DIR: path.join(process.cwd(), ".appgraph-cache-e2e-mono"),
        APPGRAPH_ANALYZE_RATE_LIMIT: "200",
        APPGRAPH_MAX_CONCURRENT_ANALYSES: "2",
        ...(process.env.NEXT_DIST_DIR ? { NEXT_DIST_DIR: process.env.NEXT_DIST_DIR } : {}),
      },
    },
  ],
});
