import path from "node:path";
import { defineConfig } from "@playwright/test";

const PORT = 3222;
const fixtureDir = path.join(process.cwd(), "tests", "fixtures", "sample-nextjs");

/**
 * E2E runs against a production build with the deterministic fixture provider,
 * so no GitHub API traffic is generated by automated tests.
 *
 * Requires a prior `npm run build`. Uses the locally installed Edge browser
 * (channel: msedge) to avoid downloading browser binaries.
 */
export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 120_000,
  expect: { timeout: 20_000 },
  fullyParallel: false,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: `http://127.0.0.1:${PORT}`,
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "msedge",
      use: {
        channel: "msedge",
        viewport: { width: 1440, height: 900 },
      },
    },
  ],
  webServer: {
    command: `node node_modules/next/dist/bin/next start -p ${PORT}`,
    url: `http://127.0.0.1:${PORT}/api/health`,
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      APPGRAPH_FIXTURE_DIR: fixtureDir,
      APPGRAPH_ANALYSIS_VERSION: "e2e",
      APPGRAPH_CACHE_DIR: path.join(process.cwd(), ".appgraph-cache-e2e"),
      APPGRAPH_ANALYZE_RATE_LIMIT: "200",
      APPGRAPH_MAX_CONCURRENT_ANALYSES: "2",
      // Optional isolated build directory (useful when a dev server is running).
      ...(process.env.NEXT_DIST_DIR ? { NEXT_DIST_DIR: process.env.NEXT_DIST_DIR } : {}),
    },
  },
});
